# Generated by Django 3.2.5 on 2021-07-18 16:10

from django.db import models, migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []  # type: ignore

    operations = [
        migrations.CreateModel(
            name="SignUpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_addr", models.GenericIPAddressField()),
                ("email", models.EmailField(max_length=254)),
                ("password", models.TextField()),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
            ],
            options={
                "verbose_name": "Sign-up request",
                "verbose_name_plural": "Sign-up requests",
                "db_table": "signup_requests",
            },
        ),
    ]
