# Generated by Django 3.2.5 on 2021-07-18 16:20

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signuprequest",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
